name: Despliegue con Evento Cron

on:
schedule:
    - cron: '30 5 * * 1,3'
    - cron: '30 5 * * 2,4'
    - cron: "*/5 * * * 1-5"

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2

    - name: Despliegue de la imagen
      run: |
        # Aquí agregarías los comandos para desplegar la imagen en tu entorno
        # Ejemplo: docker pull <nombre_de_la_imagen>
        #          docker run <opciones_de_ejecución> <nombre_de_la_imagen>

    - name: Configurar evento Cron
      run: |
        echo "0 9 * * 1-5 comando_a_ejecutar" >> ~/.cronfile  # Este ejemplo ejecuta 'comando_a_ejecutar' a las 9 AM de lunes a viernes
        crontab ~/.cronfile

      # Establecer el cron para ejecutarse de lunes a viernes a las 9:00 AM UTC
    test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Not on Monday or Wednesday
        if: github.event.schedule != '30 5 * * 1,3'
        run: echo "This step will be skipped on Monday and Wednesday"
      - name: Every time
        run: echo "This step will always run"
