#Autor - actualización : Humberto Melendez
#correo - humberto.melendez.arg@gmail.com
---
version: "4.8"

services:
  myjenkins:
    container_name: myjenkins
    image: jenkins/jenkins:lts
    user: root
    environment:
      SONARQUBE_HOST: mysonarqube
    ports:
      - "8083:8080"
    volumes:
      # Named  Docker volume details at the bottom
      - jenkins_home:/var/jenkins_home
      # WARNING:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - devops
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: 4G
  mysonarqube:
    container_name: mysonarqube
    # build: ./sonarqube_home
    image: sonarqube:10.4.1-community
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    ports:
      - "9003:9000"
    networks:
      - devops
    volumes:
      - ./sonarqube_home/conf/:/opt/sonarqube/conf
      - ./sonarqube_home/data/:/opt/sonarqube/data
      - ./sonarqube_home/logs/:/opt/sonarqube/logs
      - ./sonarqube_home/extensions/:/opt/sonarqube/extensions
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: 4G

# To use docker-volume (custom_jenkins_home) instead of a directory path-file
volumes:
  jenkins_home:
    name: "jenkins_home_v1.0"

networks:
  devops:
    driver: bridge
    name: devops
