# This is a basic workflow to help you get started with Actions

name: Despliegue con Evento Cron

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2

    - name: Despliegue de la imagen
      run: |
        # Aquí agregarías los comandos para desplegar la imagen en tu entorno
        # Ejemplo: docker pull <nombre_de_la_imagen>
        #          docker run <opciones_de_ejecución> <nombre_de_la_imagen>

    - name: Configurar evento Cron
      run: |
        echo "0 9 * * 1-5 comando_a_ejecutar" >> ~/.cronfile  # Este ejemplo ejecuta 'comando_a_ejecutar' a las 9 AM de lunes a viernes
        crontab ~/.cronfile

      # Establecer el cron para ejecutarse de lunes a viernes a las 9:00 AM UTC
