name: Validación de Horario

on:
  pull_request:
    types: [opened, synchronize,reopened,labeled,unlabeled]

jobs:
  validate_schedule:
    runs-on: ubuntu-latest

    steps:
      - name: Capturar Hora y Día
        run: |
          current_hour=$(date +"%H")
          current_day=$(date +"%u")
          
          echo "Hora actual: $current_hour"
          echo "Día actual: $current_day"
          
      - name: Capturar Zona Horaria
        run: echo "La zona horaria actual es $TZ"
